# Navigating data ontologies

```{tip}
Open this tutorial in Google colab for interactive viewing.
```

In [9]:
# @title Install AlphaGenome

# @markdown Run this cell to install AlphaGenome.
from IPython.display import clear_output
! pip install alphagenome
clear_output()

## Setup and imports

In [10]:
from alphagenome import colab_utils
from alphagenome.models import dna_client
#from google.colab import data_table
import pandas as pd

#data_table.enable_dataframe_formatter()

## Interactively view output metadata

First, we load the model.

In [ ]:
API_KEY = ""
dna_model = dna_client.create(API_KEY)

output_metadata = dna_model.output_metadata(
    dna_client.Organism.MUS_MUSCULUS
).concatenate()

Click `Filter` on the upper right hand side of the interactive dataframe and type a cell or tissue name like "brain" into the `Search by all fields box` to find the `ontology_curie` term corresponding to a tissue and output type of interest:

In [12]:
output_metadata

,name,strand,Assay title,ontology_curie,biosample_name,biosample_type,biosample_life_stage,data_source,endedness,genetically_modified,output_type,gtex_tissue,histone_mark,transcription_factor
0,CL:0000553 ATAC-seq,.,ATAC-seq,CL:0000553,megakaryocyte progenitor cell,primary_cell,adult,encode,single,False,OutputType.ATAC,NaN,NaN,NaN
1,CL:0000557 ATAC-seq,.,ATAC-seq,CL:0000557,granulocyte monocyte progenitor cell,primary_cell,adult,encode,single,False,OutputType.ATAC,NaN,NaN,NaN
2,CL:0000792 ATAC-seq,.,ATAC-seq,CL:0000792,"CD4-positive, CD25-positive, alpha-beta regula...",primary_cell,adult,encode,paired,False,OutputType.ATAC,NaN,NaN,NaN
3,EFO:0005481 ATAC-seq,.,ATAC-seq,EFO:0005481,Patski,cell_line,unknown,encode,paired,False,OutputType.ATAC,NaN,NaN,NaN
4,NTR:0004148 ATAC-seq,.,ATAC-seq,NTR:0004148,"activated CD4-positive, CD25-positive, alpha-b...",primary_cell,adult,encode,paired,False,OutputType.ATAC,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,4dn:4DNFIC21MG3U,.,in situ Hi-C,EFO:0004038,mouse embryonic stem cell,cell_line,NaN,4dnucleome,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
4,4dn:4DNFIHBTUDO9,.,in situ Hi-C,CL:0000207,olfactory receptor cell,primary_cell,NaN,4dnucleome,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
5,4dn:4DNFIKK3QG34,.,in situ Hi-C,EFO:0005484,46C,cell_line,NaN,4dnucleome,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
6,4dn:4DNFIMV54HXI,.,in situ Hi-C,CL:0000207,olfactory receptor cell,primary_cell,NaN,4dnucleome,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN
7,4dn:4DNFIS5ZK13C,.,in situ Hi-C,CL:0000945,lymphocyte of B lineage,cell_line,NaN,4dnucleome,NaN,NaN,OutputType.CONTACT_MAPS,NaN,NaN,NaN

### How many tracks are there per output type?

In [16]:
# Count human tracks
human_tracks = (
    dna_model.output_metadata(dna_client.Organism.HOMO_SAPIENS)
    .concatenate()
    .groupby('output_type')
    .size()
    .rename('# Human tracks')
)

# Count mouse tracks
mouse_tracks = (
    dna_model.output_metadata(dna_client.Organism.MUS_MUSCULUS)
    .concatenate()
    .groupby('output_type')
    .size()
    .rename('# Mouse tracks')
)

pd.concat([human_tracks, mouse_tracks], axis=1).astype(pd.Int64Dtype())

                              # Human tracks  # Mouse tracks
output_type
OutputType.ATAC                          167              18
OutputType.CAGE                          546             188
OutputType.DNASE                         305              67
OutputType.RNA_SEQ                       667             173
OutputType.CHIP_HISTONE                 1116             183
OutputType.CHIP_TF                      1617             127
OutputType.SPLICE_SITES                    4               4
OutputType.SPLICE_SITE_USAGE             734             180
OutputType.SPLICE_JUNCTIONS              367              90
OutputType.CONTACT_MAPS                   28               8
OutputType.PROCAP                         12            <NA>

In [25]:
[output.name for output in dna_client.OutputType]

['ATAC',
 'CAGE',
 'DNASE',
 'RNA_SEQ',
 'CHIP_HISTONE',
 'CHIP_TF',
 'SPLICE_SITES',
 'SPLICE_SITE_USAGE',
 'SPLICE_JUNCTIONS',
 'CONTACT_MAPS',
 'PROCAP']

In [28]:
dna_client.OutputType.RNA_SEQ

RNA_SEQ

In [ ]:
dna_client.SEQUENCE_LENGTH_100KB

In [36]:
output = dna_model.predict_sequence(
    sequence='GATTACA'.center(
        dna_client.SEQUENCE_LENGTH_1MB, 'N'
    ),  # Pad to valid sequence length.
    requested_outputs=[dna_client.OutputType.CHIP_HISTONE],
    ontology_terms=['UBERON:0002305'],  # Lung.
)

In [116]:
df_dmr_hip = pd.read_csv("/home/junyichen/code/mmllm/output/dmr_selected_HIP.csv")

In [126]:
df_dmr_hip

,mod,motif,dmr,ifdifferent,score,num_sites,effect_size,case1_sig,case2_sig,diff.Methy,...,anno,modmotif,chr,start,end,region,length,center,start_expanded,end_expanded
0,5hmC,CG,5hmC|CG_1:10107220-10107355,different,-14.868667,5,-0.182777,0.168849,0.351626,-0.182777,...,distal_135_9946118:10444118,5hmC|CG,1,10107220,10107355,HIP,135,10107287,10107220,10107355
1,5hmC,CG,5hmC|CG_1:101608410-101608460,different,-16.165365,4,-0.133099,0.041498,0.174597,-0.133099,...,distal_50_101380740:101878740,5hmC|CG,1,101608410,101608460,HIP,50,101608435,101608385,101608485
2,5hmC,CG,5hmC|CG_1:102835347-102835481,different,-16.311197,5,-0.078290,0.020423,0.098713,-0.078290,...,distal_134_102453547:102951547,5hmC|CG,1,102835347,102835481,HIP,134,102835414,102835347,102835481
3,5hmC,CG,5hmC|CG_1:103592440-103592588,different,-19.779267,7,-0.046215,0.030773,0.076987,-0.046215,...,distal_148_103224344:103722344,5hmC|CG,1,103592440,103592588,HIP,148,103592514,103592440,103592588
4,5hmC,CG,5hmC|CG_1:104028343-104028477,different,-14.470730,4,-0.206886,0.032384,0.239270,-0.206886,...,cdistal_134_103609523:104109523,5hmC|CG,1,104028343,104028477,HIP,134,104028410,104028343,104028477
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21483,5mC,CH,5mC|CH_X:57926426-57926716,different,-330.872304,101,-0.012714,0.009965,0.022678,-0.012714,...,cdistal_286_57794730:58294730,5mC|CH,X,57926426,57926716,HIP,290,57926571,57926426,57926716
21484,5mC,CH,5mC|CH_X:60941372-60941982,different,-76.090040,22,-0.012141,0.007504,0.019645,-0.012141,...,distal_62_60594698:61092698,5mC|CH,X,60941372,60941982,HIP,610,60941677,60941372,60941982
21485,5mC,CH,5mC|CH_X:63690863-63691025,different,-222.686072,69,-0.012673,0.003455,0.016127,-0.012673,...,cdistal_142_63335775:63835775,5mC|CH,X,63690863,63691025,HIP,162,63690944,63690863,63691025
21486,5mC,CH,5mC|CH_X:78589410-78589866,different,-109.166951,38,-0.012044,0.004035,0.016079,-0.012044,...,distal_107_78392705:78890705 distal_65_7836012...,5mC|CH,X,78589410,78589866,HIP,456,78589638,78589410,78589866
21487,5mC,CH,5mC|CH_X:93307956-93309782,different,678.016103,179,0.015443,0.024606,0.009163,0.015443,...,cdistal_472_93028853:93528853,5mC|CH,X,93307956,93309782,HIP,1826,93308869,93307956,93309782

In [146]:
from alphagenome.data.genome import Interval
import matplotlib.pyplot as plt
import numpy as np

In [186]:
df_dmr_hip_5mc = df_dmr_hip[df_dmr_hip['mod'] == '5mC']
df_dmr_hip_5mc.sort_values(by=['score'], inplace=False,ascending=False)

,mod,motif,dmr,ifdifferent,score,num_sites,effect_size,case1_sig,case2_sig,diff.Methy,...,anno,modmotif,chr,start,end,region,length,center,start_expanded,end_expanded
11987,5mC,CG,5mC|CG_18:12973118-12974419,different,1015.911043,214,0.076074,0.164490,0.088416,0.076074,...,cdistal_1301_12689171:13189171,5mC|CG,18,12973118,12974419,HIP,1301,12973768,12973118,12974419
20321,5mC,CG,5mC|CG_18:12972685-12974748,different,941.861845,214,0.077538,0.172217,0.094680,0.077538,...,cdistal_155_12736400:13236400 cdistal_1301_128...,5mC|CG,18,12972685,12974748,HIP,2063,12973716,12972685,12974748
18066,5mC,CH,5mC|CH_13:103917021-103917675,different,940.604701,211,0.016493,0.028003,0.011510,0.016493,...,distal_654_103787834:104285834,5mC|CH,13,103917021,103917675,HIP,654,103917348,103917021,103917675
19742,5mC,CG,5mC|CG_11:12025411-12026932,different,879.110817,209,0.049978,0.147146,0.097167,0.049978,...,cdistal_759_11937937:12437937,5mC|CG,11,12025411,12026932,HIP,1521,12026171,12025411,12026932
8952,5mC,CG,5mC|CG_11:12025820-12026579,different,879.110817,209,0.049978,0.147146,0.097167,0.049978,...,distal_759_11810962:12308962,5mC|CG,11,12025820,12026579,HIP,759,12026199,12025820,12026579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20326,5mC,CG,5mC|CG_18:30266954-30268965,different,-1735.212146,226,-0.209721,0.239824,0.449545,-0.209721,...,distal_1920_29920059:30418059,5mC|CG,18,30266954,30268965,HIP,2011,30267959,30266954,30268965
15605,5mC,CG,5mC|CG_6:28927798-28929825,different,-2006.642134,171,-0.361335,0.210212,0.571547,-0.361335,...,cdistal_2027_28714805:29214805,5mC|CG,6,28927798,28929825,HIP,2027,28928811,28927798,28929825
10544,5mC,CG,5mC|CG_14:54295637-54297753,different,-2496.117491,225,-0.318621,0.264197,0.582819,-0.318621,...,distal_2116_54164644:54662644,5mC|CG,14,54295637,54297753,HIP,2116,54296695,54295637,54297753
20042,5mC,CG,5mC|CG_14:54295626-54297753,different,-2496.117491,225,-0.318621,0.264197,0.582819,-0.318621,...,distal_2116_54140951:54638951,5mC|CG,14,54295626,54297753,HIP,2127,54296689,54295626,54297753
9138,5mC,CG,5mC|CG_11:6006145-6008350,different,-2566.795207,262,-0.219661,0.120383,0.340043,-0.219661,...,cdistal_2205_5944847:6444847,5mC|CG,11,6006145,6008350,HIP,2205,6007247,6006145,6008350

In [189]:
track1s= []
track2s = []
for index,row in df_dmr_hip_5mc.iterrows():
    chrom = f"chr{row['chr']}"
    start = row['start']
    end = row['end']
    name = row['dmr']
    #print(f"Processing {chrom}:{start}-{end}")
    # output = dna_model.predict_region(
    #     chrom=chrom,
    #     start=start,
    #     end=end,
    #     requested_outputs=[dna_client.OutputType.CHIP_HISTONE],
    #     ontology_terms=['UBERON:0002305'],  # Lung.
    # )
    #5mC|CG_11:12025411-12026932
# pad interval to 2048
# 原始信息
    chrom = chrom
    orig_start = start
    orig_end = end
    target_length = 16384
    name = name

    # 计算当前长度和所需 padding
    current_len = orig_end - orig_start
    pad_total = target_length - current_len

    # 计算左右两侧的扩展量（保持中心对齐）
    pad_left = pad_total // 2
    pad_right = pad_total - pad_left

    # 创建 Padding 后的新 Interval
    # 注意：在实际应用中，建议检查 start 是否小于 0
    new_start = max(0, orig_start - pad_left)
    new_end = new_start + target_length

    interval_padded = Interval(chrom, start=new_start, end=new_end,name=name)
    output = dna_model.predict_interval(
        
        interval=interval_padded,
        organism=dna_client.Organism.MUS_MUSCULUS,
        requested_outputs=[dna_client.OutputType.CHIP_HISTONE],
            ontology_terms=['UBERON:0002305'],  # Lung.

    )
    # plot the value of the first track
    # x start from satrt-16384/2 to end+16384/2, step = 128
    # x = np.arange(0 - target_length // 2, 0 + target_length // 2, 128)
    # plt.plot(x, output.chip_histone.values[:,0], label='Track 1 H3K27ac')
    # plt.plot(x, output.chip_histone.values[:,1], label='Track 2 H3K4me3')
    # plt.title('Predicted CHIP_HISTONE signal')
    # plt.xlabel('Position (bp)')
    # plt.ylabel('Signal')
    # plt.legend()
    # plt.show()
    # print(f"Predicted CHIP_HISTONE signal shape: {output.chip_histone.values.shape}")
    track1s.append(output.chip_histone.values[:,0])
    track2s.append(output.chip_histone.values[:,1])

In [17]:
output_metadata.to_csv('output/mouse_tracks.csv', index=False)

Note that `PROCAP` outputs are not available for mouse.